default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost

development:
  <<: *default
  database: simple_logger_server-development

production:
  <<: *default
  database: <%= ENV['DB_NAME'] || "simple_logger_server-production" %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *default
  database: simple_logger_server-test
